//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileTransferClient.FileTransfer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileTransfer.FileTransferSoap")]
    public interface FileTransferSoap {
        
        // CODEGEN: Generating message contract since element name docbinaryarray from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDocument", ReplyAction="*")]
        FileTransferClient.FileTransfer.SaveDocumentResponse SaveDocument(FileTransferClient.FileTransfer.SaveDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.SaveDocumentResponse> SaveDocumentAsync(FileTransferClient.FileTransfer.SaveDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewUser", ReplyAction="*")]
        FileTransferClient.FileTransfer.NewUserResponse NewUser(FileTransferClient.FileTransfer.NewUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewUser", ReplyAction="*")]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.NewUserResponse> NewUserAsync(FileTransferClient.FileTransfer.NewUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUser", ReplyAction="*")]
        FileTransferClient.FileTransfer.LoginUserResponse LoginUser(FileTransferClient.FileTransfer.LoginUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUser", ReplyAction="*")]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.LoginUserResponse> LoginUserAsync(FileTransferClient.FileTransfer.LoginUserRequest request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileStruture", ReplyAction="*")]
        FileTransferClient.FileTransfer.GetFileStrutureResponse GetFileStruture(FileTransferClient.FileTransfer.GetFileStrutureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileStruture", ReplyAction="*")]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.GetFileStrutureResponse> GetFileStrutureAsync(FileTransferClient.FileTransfer.GetFileStrutureRequest request);
        
        // CODEGEN: Generating message contract since element name DocumentName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentLen", ReplyAction="*")]
        FileTransferClient.FileTransfer.GetDocumentLenResponse GetDocumentLen(FileTransferClient.FileTransfer.GetDocumentLenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentLen", ReplyAction="*")]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.GetDocumentLenResponse> GetDocumentLenAsync(FileTransferClient.FileTransfer.GetDocumentLenRequest request);
        
        // CODEGEN: Generating message contract since element name DocumentName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocument", ReplyAction="*")]
        FileTransferClient.FileTransfer.GetDocumentResponse GetDocument(FileTransferClient.FileTransfer.GetDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.GetDocumentResponse> GetDocumentAsync(FileTransferClient.FileTransfer.GetDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name DocumentName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDocument", ReplyAction="*")]
        FileTransferClient.FileTransfer.DeleteDocumentResponse DeleteDocument(FileTransferClient.FileTransfer.DeleteDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.DeleteDocumentResponse> DeleteDocumentAsync(FileTransferClient.FileTransfer.DeleteDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name DocumentName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewFolder", ReplyAction="*")]
        FileTransferClient.FileTransfer.NewFolderResponse NewFolder(FileTransferClient.FileTransfer.NewFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewFolder", ReplyAction="*")]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.NewFolderResponse> NewFolderAsync(FileTransferClient.FileTransfer.NewFolderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDocument", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.SaveDocumentRequestBody Body;
        
        public SaveDocumentRequest() {
        }
        
        public SaveDocumentRequest(FileTransferClient.FileTransfer.SaveDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] docbinaryarray;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string docname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string path;
        
        public SaveDocumentRequestBody() {
        }
        
        public SaveDocumentRequestBody(byte[] docbinaryarray, string docname, string path) {
            this.docbinaryarray = docbinaryarray;
            this.docname = docname;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.SaveDocumentResponseBody Body;
        
        public SaveDocumentResponse() {
        }
        
        public SaveDocumentResponse(FileTransferClient.FileTransfer.SaveDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveDocumentResult;
        
        public SaveDocumentResponseBody() {
        }
        
        public SaveDocumentResponseBody(bool SaveDocumentResult) {
            this.SaveDocumentResult = SaveDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewUser", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.NewUserRequestBody Body;
        
        public NewUserRequest() {
        }
        
        public NewUserRequest(FileTransferClient.FileTransfer.NewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public NewUserRequestBody() {
        }
        
        public NewUserRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.NewUserResponseBody Body;
        
        public NewUserResponse() {
        }
        
        public NewUserResponse(FileTransferClient.FileTransfer.NewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool NewUserResult;
        
        public NewUserResponseBody() {
        }
        
        public NewUserResponseBody(bool NewUserResult) {
            this.NewUserResult = NewUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUser", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.LoginUserRequestBody Body;
        
        public LoginUserRequest() {
        }
        
        public LoginUserRequest(FileTransferClient.FileTransfer.LoginUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public LoginUserRequestBody() {
        }
        
        public LoginUserRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.LoginUserResponseBody Body;
        
        public LoginUserResponse() {
        }
        
        public LoginUserResponse(FileTransferClient.FileTransfer.LoginUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginUserResult;
        
        public LoginUserResponseBody() {
        }
        
        public LoginUserResponseBody(bool LoginUserResult) {
            this.LoginUserResult = LoginUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileStrutureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileStruture", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.GetFileStrutureRequestBody Body;
        
        public GetFileStrutureRequest() {
        }
        
        public GetFileStrutureRequest(FileTransferClient.FileTransfer.GetFileStrutureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileStrutureRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        public GetFileStrutureRequestBody() {
        }
        
        public GetFileStrutureRequestBody(string source) {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileStrutureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileStrutureResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.GetFileStrutureResponseBody Body;
        
        public GetFileStrutureResponse() {
        }
        
        public GetFileStrutureResponse(FileTransferClient.FileTransfer.GetFileStrutureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileStrutureResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileStrutureResult;
        
        public GetFileStrutureResponseBody() {
        }
        
        public GetFileStrutureResponseBody(string GetFileStrutureResult) {
            this.GetFileStrutureResult = GetFileStrutureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentLenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentLen", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.GetDocumentLenRequestBody Body;
        
        public GetDocumentLenRequest() {
        }
        
        public GetDocumentLenRequest(FileTransferClient.FileTransfer.GetDocumentLenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocumentLenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocumentName;
        
        public GetDocumentLenRequestBody() {
        }
        
        public GetDocumentLenRequestBody(string DocumentName) {
            this.DocumentName = DocumentName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentLenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentLenResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.GetDocumentLenResponseBody Body;
        
        public GetDocumentLenResponse() {
        }
        
        public GetDocumentLenResponse(FileTransferClient.FileTransfer.GetDocumentLenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocumentLenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetDocumentLenResult;
        
        public GetDocumentLenResponseBody() {
        }
        
        public GetDocumentLenResponseBody(int GetDocumentLenResult) {
            this.GetDocumentLenResult = GetDocumentLenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocument", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.GetDocumentRequestBody Body;
        
        public GetDocumentRequest() {
        }
        
        public GetDocumentRequest(FileTransferClient.FileTransfer.GetDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocumentName;
        
        public GetDocumentRequestBody() {
        }
        
        public GetDocumentRequestBody(string DocumentName) {
            this.DocumentName = DocumentName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.GetDocumentResponseBody Body;
        
        public GetDocumentResponse() {
        }
        
        public GetDocumentResponse(FileTransferClient.FileTransfer.GetDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetDocumentResult;
        
        public GetDocumentResponseBody() {
        }
        
        public GetDocumentResponseBody(byte[] GetDocumentResult) {
            this.GetDocumentResult = GetDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDocument", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.DeleteDocumentRequestBody Body;
        
        public DeleteDocumentRequest() {
        }
        
        public DeleteDocumentRequest(FileTransferClient.FileTransfer.DeleteDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocumentName;
        
        public DeleteDocumentRequestBody() {
        }
        
        public DeleteDocumentRequestBody(string DocumentName) {
            this.DocumentName = DocumentName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.DeleteDocumentResponseBody Body;
        
        public DeleteDocumentResponse() {
        }
        
        public DeleteDocumentResponse(FileTransferClient.FileTransfer.DeleteDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteDocumentResponseBody {
        
        public DeleteDocumentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewFolderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewFolder", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.NewFolderRequestBody Body;
        
        public NewFolderRequest() {
        }
        
        public NewFolderRequest(FileTransferClient.FileTransfer.NewFolderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewFolderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DocumentName;
        
        public NewFolderRequestBody() {
        }
        
        public NewFolderRequestBody(string DocumentName) {
            this.DocumentName = DocumentName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewFolderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewFolderResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileTransferClient.FileTransfer.NewFolderResponseBody Body;
        
        public NewFolderResponse() {
        }
        
        public NewFolderResponse(FileTransferClient.FileTransfer.NewFolderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewFolderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool NewFolderResult;
        
        public NewFolderResponseBody() {
        }
        
        public NewFolderResponseBody(bool NewFolderResult) {
            this.NewFolderResult = NewFolderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileTransferSoapChannel : FileTransferClient.FileTransfer.FileTransferSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileTransferSoapClient : System.ServiceModel.ClientBase<FileTransferClient.FileTransfer.FileTransferSoap>, FileTransferClient.FileTransfer.FileTransferSoap {
        
        public FileTransferSoapClient() {
        }
        
        public FileTransferSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileTransferSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransferSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransferSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileTransferClient.FileTransfer.SaveDocumentResponse FileTransferClient.FileTransfer.FileTransferSoap.SaveDocument(FileTransferClient.FileTransfer.SaveDocumentRequest request) {
            return base.Channel.SaveDocument(request);
        }
        
        public bool SaveDocument(byte[] docbinaryarray, string docname, string path) {
            FileTransferClient.FileTransfer.SaveDocumentRequest inValue = new FileTransferClient.FileTransfer.SaveDocumentRequest();
            inValue.Body = new FileTransferClient.FileTransfer.SaveDocumentRequestBody();
            inValue.Body.docbinaryarray = docbinaryarray;
            inValue.Body.docname = docname;
            inValue.Body.path = path;
            FileTransferClient.FileTransfer.SaveDocumentResponse retVal = ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).SaveDocument(inValue);
            return retVal.Body.SaveDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.SaveDocumentResponse> FileTransferClient.FileTransfer.FileTransferSoap.SaveDocumentAsync(FileTransferClient.FileTransfer.SaveDocumentRequest request) {
            return base.Channel.SaveDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileTransferClient.FileTransfer.SaveDocumentResponse> SaveDocumentAsync(byte[] docbinaryarray, string docname, string path) {
            FileTransferClient.FileTransfer.SaveDocumentRequest inValue = new FileTransferClient.FileTransfer.SaveDocumentRequest();
            inValue.Body = new FileTransferClient.FileTransfer.SaveDocumentRequestBody();
            inValue.Body.docbinaryarray = docbinaryarray;
            inValue.Body.docname = docname;
            inValue.Body.path = path;
            return ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).SaveDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileTransferClient.FileTransfer.NewUserResponse FileTransferClient.FileTransfer.FileTransferSoap.NewUser(FileTransferClient.FileTransfer.NewUserRequest request) {
            return base.Channel.NewUser(request);
        }
        
        public bool NewUser(string username) {
            FileTransferClient.FileTransfer.NewUserRequest inValue = new FileTransferClient.FileTransfer.NewUserRequest();
            inValue.Body = new FileTransferClient.FileTransfer.NewUserRequestBody();
            inValue.Body.username = username;
            FileTransferClient.FileTransfer.NewUserResponse retVal = ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).NewUser(inValue);
            return retVal.Body.NewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.NewUserResponse> FileTransferClient.FileTransfer.FileTransferSoap.NewUserAsync(FileTransferClient.FileTransfer.NewUserRequest request) {
            return base.Channel.NewUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileTransferClient.FileTransfer.NewUserResponse> NewUserAsync(string username) {
            FileTransferClient.FileTransfer.NewUserRequest inValue = new FileTransferClient.FileTransfer.NewUserRequest();
            inValue.Body = new FileTransferClient.FileTransfer.NewUserRequestBody();
            inValue.Body.username = username;
            return ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).NewUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileTransferClient.FileTransfer.LoginUserResponse FileTransferClient.FileTransfer.FileTransferSoap.LoginUser(FileTransferClient.FileTransfer.LoginUserRequest request) {
            return base.Channel.LoginUser(request);
        }
        
        public bool LoginUser(string username) {
            FileTransferClient.FileTransfer.LoginUserRequest inValue = new FileTransferClient.FileTransfer.LoginUserRequest();
            inValue.Body = new FileTransferClient.FileTransfer.LoginUserRequestBody();
            inValue.Body.username = username;
            FileTransferClient.FileTransfer.LoginUserResponse retVal = ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).LoginUser(inValue);
            return retVal.Body.LoginUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.LoginUserResponse> FileTransferClient.FileTransfer.FileTransferSoap.LoginUserAsync(FileTransferClient.FileTransfer.LoginUserRequest request) {
            return base.Channel.LoginUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileTransferClient.FileTransfer.LoginUserResponse> LoginUserAsync(string username) {
            FileTransferClient.FileTransfer.LoginUserRequest inValue = new FileTransferClient.FileTransfer.LoginUserRequest();
            inValue.Body = new FileTransferClient.FileTransfer.LoginUserRequestBody();
            inValue.Body.username = username;
            return ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).LoginUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileTransferClient.FileTransfer.GetFileStrutureResponse FileTransferClient.FileTransfer.FileTransferSoap.GetFileStruture(FileTransferClient.FileTransfer.GetFileStrutureRequest request) {
            return base.Channel.GetFileStruture(request);
        }
        
        public string GetFileStruture(string source) {
            FileTransferClient.FileTransfer.GetFileStrutureRequest inValue = new FileTransferClient.FileTransfer.GetFileStrutureRequest();
            inValue.Body = new FileTransferClient.FileTransfer.GetFileStrutureRequestBody();
            inValue.Body.source = source;
            FileTransferClient.FileTransfer.GetFileStrutureResponse retVal = ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).GetFileStruture(inValue);
            return retVal.Body.GetFileStrutureResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.GetFileStrutureResponse> FileTransferClient.FileTransfer.FileTransferSoap.GetFileStrutureAsync(FileTransferClient.FileTransfer.GetFileStrutureRequest request) {
            return base.Channel.GetFileStrutureAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileTransferClient.FileTransfer.GetFileStrutureResponse> GetFileStrutureAsync(string source) {
            FileTransferClient.FileTransfer.GetFileStrutureRequest inValue = new FileTransferClient.FileTransfer.GetFileStrutureRequest();
            inValue.Body = new FileTransferClient.FileTransfer.GetFileStrutureRequestBody();
            inValue.Body.source = source;
            return ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).GetFileStrutureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileTransferClient.FileTransfer.GetDocumentLenResponse FileTransferClient.FileTransfer.FileTransferSoap.GetDocumentLen(FileTransferClient.FileTransfer.GetDocumentLenRequest request) {
            return base.Channel.GetDocumentLen(request);
        }
        
        public int GetDocumentLen(string DocumentName) {
            FileTransferClient.FileTransfer.GetDocumentLenRequest inValue = new FileTransferClient.FileTransfer.GetDocumentLenRequest();
            inValue.Body = new FileTransferClient.FileTransfer.GetDocumentLenRequestBody();
            inValue.Body.DocumentName = DocumentName;
            FileTransferClient.FileTransfer.GetDocumentLenResponse retVal = ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).GetDocumentLen(inValue);
            return retVal.Body.GetDocumentLenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.GetDocumentLenResponse> FileTransferClient.FileTransfer.FileTransferSoap.GetDocumentLenAsync(FileTransferClient.FileTransfer.GetDocumentLenRequest request) {
            return base.Channel.GetDocumentLenAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileTransferClient.FileTransfer.GetDocumentLenResponse> GetDocumentLenAsync(string DocumentName) {
            FileTransferClient.FileTransfer.GetDocumentLenRequest inValue = new FileTransferClient.FileTransfer.GetDocumentLenRequest();
            inValue.Body = new FileTransferClient.FileTransfer.GetDocumentLenRequestBody();
            inValue.Body.DocumentName = DocumentName;
            return ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).GetDocumentLenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileTransferClient.FileTransfer.GetDocumentResponse FileTransferClient.FileTransfer.FileTransferSoap.GetDocument(FileTransferClient.FileTransfer.GetDocumentRequest request) {
            return base.Channel.GetDocument(request);
        }
        
        public byte[] GetDocument(string DocumentName) {
            FileTransferClient.FileTransfer.GetDocumentRequest inValue = new FileTransferClient.FileTransfer.GetDocumentRequest();
            inValue.Body = new FileTransferClient.FileTransfer.GetDocumentRequestBody();
            inValue.Body.DocumentName = DocumentName;
            FileTransferClient.FileTransfer.GetDocumentResponse retVal = ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).GetDocument(inValue);
            return retVal.Body.GetDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.GetDocumentResponse> FileTransferClient.FileTransfer.FileTransferSoap.GetDocumentAsync(FileTransferClient.FileTransfer.GetDocumentRequest request) {
            return base.Channel.GetDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileTransferClient.FileTransfer.GetDocumentResponse> GetDocumentAsync(string DocumentName) {
            FileTransferClient.FileTransfer.GetDocumentRequest inValue = new FileTransferClient.FileTransfer.GetDocumentRequest();
            inValue.Body = new FileTransferClient.FileTransfer.GetDocumentRequestBody();
            inValue.Body.DocumentName = DocumentName;
            return ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).GetDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileTransferClient.FileTransfer.DeleteDocumentResponse FileTransferClient.FileTransfer.FileTransferSoap.DeleteDocument(FileTransferClient.FileTransfer.DeleteDocumentRequest request) {
            return base.Channel.DeleteDocument(request);
        }
        
        public void DeleteDocument(string DocumentName) {
            FileTransferClient.FileTransfer.DeleteDocumentRequest inValue = new FileTransferClient.FileTransfer.DeleteDocumentRequest();
            inValue.Body = new FileTransferClient.FileTransfer.DeleteDocumentRequestBody();
            inValue.Body.DocumentName = DocumentName;
            FileTransferClient.FileTransfer.DeleteDocumentResponse retVal = ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).DeleteDocument(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.DeleteDocumentResponse> FileTransferClient.FileTransfer.FileTransferSoap.DeleteDocumentAsync(FileTransferClient.FileTransfer.DeleteDocumentRequest request) {
            return base.Channel.DeleteDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileTransferClient.FileTransfer.DeleteDocumentResponse> DeleteDocumentAsync(string DocumentName) {
            FileTransferClient.FileTransfer.DeleteDocumentRequest inValue = new FileTransferClient.FileTransfer.DeleteDocumentRequest();
            inValue.Body = new FileTransferClient.FileTransfer.DeleteDocumentRequestBody();
            inValue.Body.DocumentName = DocumentName;
            return ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).DeleteDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileTransferClient.FileTransfer.NewFolderResponse FileTransferClient.FileTransfer.FileTransferSoap.NewFolder(FileTransferClient.FileTransfer.NewFolderRequest request) {
            return base.Channel.NewFolder(request);
        }
        
        public bool NewFolder(string DocumentName) {
            FileTransferClient.FileTransfer.NewFolderRequest inValue = new FileTransferClient.FileTransfer.NewFolderRequest();
            inValue.Body = new FileTransferClient.FileTransfer.NewFolderRequestBody();
            inValue.Body.DocumentName = DocumentName;
            FileTransferClient.FileTransfer.NewFolderResponse retVal = ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).NewFolder(inValue);
            return retVal.Body.NewFolderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileTransferClient.FileTransfer.NewFolderResponse> FileTransferClient.FileTransfer.FileTransferSoap.NewFolderAsync(FileTransferClient.FileTransfer.NewFolderRequest request) {
            return base.Channel.NewFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileTransferClient.FileTransfer.NewFolderResponse> NewFolderAsync(string DocumentName) {
            FileTransferClient.FileTransfer.NewFolderRequest inValue = new FileTransferClient.FileTransfer.NewFolderRequest();
            inValue.Body = new FileTransferClient.FileTransfer.NewFolderRequestBody();
            inValue.Body.DocumentName = DocumentName;
            return ((FileTransferClient.FileTransfer.FileTransferSoap)(this)).NewFolderAsync(inValue);
        }
    }
}
